Feature/signup 회원 가입 기능 완료 PR부탁드립니다.
QG-LN/Quantum-Tec pull request #17
Opened 2023-05-13 01:19 UTC by MayoneJY

비밀번호 암호화를 제외한 나머지 부분 기능 완료 되었으니 PR 부탁드립니다.

2023-05-13 07:14 UTC, jeonghyeok-Lee commented on QuantumTec/src/main/resources/mapper/userMapper.xml
> +    <select id="selectCountById" resultType="int">
현재 사용중인 userInfo 테이블의 경우 닉네임과 ID는 모두 Unique 키로써 사용중이기 때문에 집계함수인 COUNT()가 아닌 user_idx만 호출하여도 비교가 가능합니다.

2023-05-13 07:42 UTC, jeonghyeok-Lee commented
전체적으로 주석의

2023-05-13 07:42 UTC, jeonghyeok-Lee requested changes

2023-05-13 07:42 UTC, jeonghyeok-Lee commented on QuantumTec/src/main/java/com/project/quantumtec/DAO/user/UserDAOImpl.java
>      }
현재 해당 코드들은 반환된 값이 0보다 클 경우에 대한 boolean 값을 전달하고 있습니다. 
하지만 sqlSession.selectOne()의 반환 값이 null일 경우 즉, sql문으로부터 아무런 값이 전달받지 못하였을 경우 NullPointerException오류가 발생할 수 있기에
null에 대한 예외 상황 처리가 필요하다고 생각듭니다.

2023-05-13 07:42 UTC, jeonghyeok-Lee commented on QuantumTec/src/main/resources/mapper/userMapper.xml
> +    </select>
현재 사용중인 userInfo 테이블의 경우 닉네임과 ID는 모두 Unique 키로써 사용중이기 때문에 집계함수인 COUNT()가 아닌 user_idx만 호출하여도 비교가 가능합니다.

2023-05-13 07:42 UTC, jeonghyeok-Lee commented on QuantumTec/src/main/java/com/project/quantumtec/Controller/MainController.java
> +    }
일반적으로 스프링부트에서 컨트롤러에서 다른 컨트롤러를 연결하는 것은 좋은 방법이 아닙니다.
MainController에서 UserController를 불러와서 사용하는 것이 아닌 UserController에 @RequestMapping("/api/user")을 부여하여 해당 경로로 매핑이 진행되게 해주고 UserController에서 아래의 기능들이 수행되도록해주는 것이 좋을 것 같습니다.

2023-05-13 07:53 UTC, jeonghyeok-Lee commented on QuantumTec/src/main/resources/mapper/userMapper.xml
> +    </select>
DAO에서 return ((Integer) sqlSession.selectOne("UserService.selectCountByNickname", user)) > 0; 와 같이 사용하기 편하도록 설정한것이기에 문제는 크게 없으나 해당 테이블에 존재하는 데이터 양이 커질수록 COUNT()를 사용하면 처리 속도가 감소할 수 있기에 변경하는게 좋을 것 같다라는 의견입니다.

2023-05-13 09:59 UTC, MayoneJY commented on QuantumTec/src/main/java/com/project/quantumtec/DAO/user/UserDAOImpl.java
>      }
듣고 보니 null에 대한 예외 상황 처리를 하지 않았네요. 처리를 하도록 반영하겠습니다.

2023-05-13 09:59 UTC, MayoneJY commented on QuantumTec/src/main/resources/mapper/userMapper.xml
> +    </select>
> DAO에서 return ((Integer) sqlSession.selectOne("UserService.selectCountByNickname", user)) > 0; 와 같이 사용하기 편하도록 설정한것이기에 문제는 크게 없으나 해당 테이블에 존재하는 데이터 양이 커질수록 COUNT()를 사용하면 처리 속도가 감소할 수 있기에 변경하는게 좋을 것 같다라는 의견입니다.

좋은 생각인 것 같습니다. null과 비교를 하는 것으로만 처리 하겠습니다.

2023-05-13 10:02 UTC, MayoneJY commented on QuantumTec/src/main/java/com/project/quantumtec/Controller/MainController.java
> +    }
> 일반적으로 스프링부트에서 컨트롤러에서 다른 컨트롤러를 연결하는 것은 좋은 방법이 아닙니다. MainController에서 UserController를 불러와서 사용하는 것이 아닌 UserController에 @RequestMapping("/api/user")을 부여하여 해당 경로로 매핑이 진행되게 해주고 UserController에서 아래의 기능들이 수행되도록해주는 것이 좋을 것 같습니다.

저번에 이야기할 때도 main -> user 컨트롤러로 가는 것이 맞느냐고 물어보았지만 이런 식으로 분리하는 게 좋을 것 같다고 답변을 들은 것 같은데 서로 다른 이야기를 하고 있었던 것으로 보입니다. 따로 연락드릴 테니 한번 이야기해 보는 것이 좋아 보입니다.

2023-05-13 13:10 UTC, MayoneJY commented
해당 요청을 수정 조치 하였으니 확인 부탁드립니다.

2023-05-14 01:39 UTC, jeonghyeok-Lee approved these changes
병합을 진행하도록 하겠습니다.

2023-05-14 01:48 UTC, merged